import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const projects = [
  {
    id: 1,
    title: "AI Weather Platform",
    category: "AI",
    description: "Real-time AI-powered weather forecasting with natural language queries, predictive analytics, and hyper-local precision.",
    image: "/projects/weather.jpg",
    features: ["Natural Language Queries", "Hyper-local Forecasting", "Predictive Analytics", "Real-time Data"],
    tech: ["Next.js", "OpenAI", "Python", "FastAPI", "PostgreSQL"],
    demo: "https://weather-web-ruby-psi.vercel.app/",
    github: "https://github.com/MuhammadAqib2310/weather",
    metrics: { score: "98/100", type: "AI + Web", status: "Live ✓" },
  },
  {
    id: 2,
    title: "BrainGrid Dashboard",
    category: "SaaS",
    description: "Multi-tenant enterprise analytics dashboard with real-time data visualization, role-based access control, and AI insights.",
    image: "/projects/dashboard.jpg",
    features: ["Multi-tenant Architecture", "Real-time Analytics", "RBAC System", "AI Insights"],
    tech: ["React", "TypeScript", "Node.js", "Redis", "MongoDB"],
    demo: "https://braingrid.vercel.app",
    github: "https://github.com/MuhammadAqib2310/braingrid",
    metrics: { score: "96/100", type: "SaaS", status: "Live ✓" },
  },
  {
    id: 3,
    title: "Qrypta AI",
    category: "AI",
    description: "Advanced AI encryption and data security platform with intelligent threat detection and automated compliance reporting.",
    image: "/projects/qrypta.jpg",
    features: ["AI Threat Detection", "Auto Encryption", "Compliance Reports", "Zero Trust Security"],
    tech: ["Python", "TensorFlow", "Next.js", "AWS", "Blockchain"],
    demo: "https://qrypta-ai.vercel.app",
    github: "https://github.com/MuhammadAqib2310/qrypta-ai",
    metrics: { score: "99/100", type: "AI Security", status: "Live ✓" },
  },
  {
    id: 4,
    title: "Nexora AI",
    category: "AI Agent",
    description: "Autonomous AI agent platform for business process automation with multi-model orchestration and workflow intelligence.",
    image: "/projects/nexora.jpg",
    features: ["Multi-Agent Orchestration", "Auto Workflow", "LLM Integration", "Real-time Processing"],
    tech: ["LangChain", "OpenAI", "FastAPI", "React", "Celery"],
    demo: "https://nexora-ai-ten-mu.vercel.app/",
    github: "https://github.com/MuhammadAqib2310/nexora-ai",
    metrics: { score: "97/100", type: "AI Agent", status: "Live ✓" },
  },
  {
    id: 5,
    title: "Apex AI — Trading Assistant",
    category: "AI",
    description: "Full-stack AI-powered trading & market analysis assistant using Google Gemini API with real-time market data, trading journal, price alerts, and JWT-secured auth.",
    image: "/projects/apex.jpg",
    features: ["Gemini AI Analysis", "Real-time Market Data", "Trading Journal", "Price Alerts"],
    tech: ["Node.js", "Express", "MongoDB", "Gemini API", "CoinGecko"],
    demo: "https://apex-ai-seven.vercel.app",
    github: "https://github.com/MuhammadAqib2310/apex-ai",
    metrics: { score: "96/100", type: "AI Trading", status: "Live ✓" },
  },
  {
    id: 6,
    title: "AI Lead Generation SaaS",
    category: "SaaS",
    description: "Full-stack AI-powered B2B lead generation platform with JWT auth, OpenAI-driven lead scoring, PostgreSQL/SQLAlchemy backend, and Stripe subscription billing.",
    image: "/projects/lead.jpg",
    features: ["OpenAI Lead Scoring", "JWT Authentication", "Stripe Billing", "B2B Pipeline"],
    tech: ["Next.js", "FastAPI", "Python", "PostgreSQL", "OpenAI"],
    demo: "https://github.com/MuhammadAqib2310/lead",
    github: "https://github.com/MuhammadAqib2310/lead",
    metrics: { score: "94/100", type: "SaaS + AI", status: "Built ✓" },
  },
  {
    id: 7,
    title: "Qanoon Bridge",
    category: "SaaS",
    description: "Multi-tenant AI-assisted Legal-Tech SaaS platform connecting citizens with verified lawyers across Pakistan, built with Next.js, React, TypeScript, and PostgreSQL.",
    image: "/projects/qanoon.jpg",
    features: ["Multi-tenant Platform", "AI Legal Assistance", "Lawyer Verification", "Case Management"],
    tech: ["Next.js", "TypeScript", "React", "Express.js", "PostgreSQL"],
    demo: "https://github.com/MuhammadAqib2310",
    github: "https://github.com/MuhammadAqib2310",
    metrics: { score: "97/100", type: "Legal SaaS", status: "Built ✓" },
  },
  {
    id: 8,
    title: "PhytoPathometric App",
    category: "AI",
    description: "Cross-platform (web + Android) plant disease detection app using React 19, TypeScript, and Python FastAPI backend with OpenCV, scikit-image, and CIELAB color-space analysis.",
    image: "/projects/phyto.jpg",
    features: ["Disease Detection", "OpenCV + CIELAB", "Android + Web", "Leaf Health Assessment"],
    tech: ["React 19", "TypeScript", "FastAPI", "Python", "OpenCV"],
    demo: "https://github.com/MuhammadAqib2310",
    github: "https://github.com/MuhammadAqib2310",
    metrics: { score: "95/100", type: "AI Vision", status: "Built ✓" },
  },
];

export const services = [
  { icon: "🤖", title: "AI Agents", desc: "Autonomous AI agents that think, decide, and execute complex tasks without human intervention." },
  { icon: "⚡", title: "Workflow Automation", desc: "End-to-end business process automation with intelligent orchestration and real-time monitoring." },
  { icon: "🚀", title: "SaaS Development", desc: "Production-ready SaaS platforms with multi-tenancy, billing, and enterprise-grade security." },
  { icon: "🧠", title: "LLM Integration", desc: "Seamless integration of GPT-4, Claude, Gemini, and custom fine-tuned models into your products." },
  { icon: "💬", title: "Voice AI", desc: "Human-like voice AI systems with real-time synthesis, emotion detection, and multi-language support." },
  { icon: "📊", title: "Data Engineering", desc: "Real-time data pipelines, analytics dashboards, and predictive modeling at enterprise scale." },
];

export const techStack = [
  { name: "Next.js", level: 95 },
  { name: "TypeScript", level: 92 },
  { name: "Python", level: 90 },
  { name: "OpenAI API", level: 95 },
  { name: "LangChain", level: 88 },
  { name: "React", level: 93 },
  { name: "Node.js", level: 89 },
  { name: "FastAPI", level: 87 },
  { name: "PostgreSQL", level: 85 },
  { name: "AWS", level: 82 },
  { name: "Docker", level: 84 },
  { name: "Supabase", level: 90 },
];

// kept for backward compat — Testimonials section not shown
export const testimonials: { name: string; role: string; avatar: string; text: string; rating: number }[] = [
  {
    name: "James Mitchell",
    role: "CEO, TechVenture USA",
    avatar: "JM",
    text: "Aqib built our entire AI agent platform in under 3 weeks. The quality was exceptional — clean code, great communication, and delivered exactly what we envisioned. Highly recommend.",
    rating: 5,
  },
  {
    name: "Sarah Al-Rashid",
    role: "Founder, SaaS Startup — UAE",
    avatar: "SA",
    text: "We hired Aqib to integrate LangChain into our existing product. He went above and beyond, suggesting improvements we hadn't even thought of. The results were outstanding.",
    rating: 5,
  },
  {
    name: "David Thompson",
    role: "CTO, FinTech Company — UK",
    avatar: "DT",
    text: "Absolutely brilliant work. Our AI-powered CRM was delivered on time, within budget, and the code quality was production-grade. Will definitely work with Aqib again.",
    rating: 5,
  },
  {
    name: "Priya Sharma",
    role: "Product Manager — Canada",
    avatar: "PS",
    text: "Aqib is one of the most reliable developers I've worked with. He built our voice AI system from scratch, handled all edge cases, and provided great post-launch support.",
    rating: 5,
  },
];
